### ISSUE TITLE
makefile borked

### ISSUE THREAD

**Issue by Frotty** [wurstscript/wurst-jar-wrapper#6]
https://github.com/wurstscript/wurst-jar-wrapper/blob/master/Makefile.toml#L9

- Tasks reference the wrong jars.
- Echo borked on windows. working version: 'echo "wurstsetup.jar" > src/jar.tmp',
- There is no grill.jar, it's wurstsetup.jar
- Forwarded run arguments: ["help"] <- remove this

**Comment by Cokemonkey11** [comment]
Thanks for the ticket. Tracking in #7, #8, and #9.

Closing out.
