### ISSUE TITLE
Cargo-make makefile doesn't work on some platforms

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/wurst-jar-wrapper#7]
> working version: `'echo "wurstsetup.jar" > src/jar.tmp'`

> "Echo borked on windows"

I think the user is using cmd or powershell ISE, with a rust installation that doesn't use msys2.

**Comment by Cokemonkey11** [comment]
* https://github.com/wurstscript/wurst-jar-wrapper/blob/master/Makefile.toml
* https://github.com/sagiegurari/cargo-make#commands-scripts-and-sub-tasks
* https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-examplerust

**Comment by Cokemonkey11** [comment]
Naively, running `echo \"hello\" > out.tmp` in cmd.exe does include the double-quotes.

**Comment by Cokemonkey11** [comment]
@frotty how did you install Rust? What terminal did you use to call cargo make? Was it powershell?

**Comment by Frotty** [comment]
Via the command from the readme (rustup)

**Comment by Cokemonkey11** [comment]
@Frotty so you used `rustup-init.exe` instead of WSL or Msys2?

**Comment by Frotty** [comment]
of course

**Comment by Cokemonkey11** [comment]
@Frotty I was too lazy to spin up a VM and repro the problem, but your suggested workaround works fine on msys2, which is good enough for me.

See #12
