### ISSUE TITLE
"Forwarded run arguments" println is more noise than signal

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/wurst-jar-wrapper#9]
> Forwarded run arguments: ["help"] <- remove this

**Comment by Cokemonkey11** [comment]
@Frotty please can you review 7d6988d

**Comment by Frotty** [comment]
We don't need reviews for 1 line changes. You can just commit this to master. It's not gonna be used for some time anyway

**Comment by Cokemonkey11** [comment]
I'm going to take that as you having reviewed it.

Code review isn't only for checking if the code works. It's for checking if we've successfully understood the specification.

**Comment by Frotty** [comment]
There was no PR, so yea

**Comment by Cokemonkey11** [comment]
@Frotty yes there was - https://github.com/wurstscript/wurst-jar-wrapper/pull/11
